// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: s_execution.proto

package rpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MRunStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId        int32                `protobuf:"varint,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	RunShuffle     bool                 `protobuf:"varint,2,opt,name=runShuffle,proto3" json:"runShuffle,omitempty"`
	PrepCollect    bool                 `protobuf:"varint,3,opt,name=prepCollect,proto3" json:"prepCollect,omitempty"`
	PrepAccumulate bool                 `protobuf:"varint,4,opt,name=prepAccumulate,proto3" json:"prepAccumulate,omitempty"`
	AssignedBucket uint64               `protobuf:"varint,5,opt,name=assignedBucket,proto3" json:"assignedBucket,omitempty"`
	Buckets        []uint64             `protobuf:"varint,6,rep,packed,name=buckets,proto3" json:"buckets,omitempty"`
	Workers        []*MWorkerDescriptor `protobuf:"bytes,7,rep,name=workers,proto3" json:"workers,omitempty"`
}

func (x *MRunStageRequest) Reset() {
	*x = MRunStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_execution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MRunStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRunStageRequest) ProtoMessage() {}

func (x *MRunStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_s_execution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRunStageRequest.ProtoReflect.Descriptor instead.
func (*MRunStageRequest) Descriptor() ([]byte, []int) {
	return file_s_execution_proto_rawDescGZIP(), []int{0}
}

func (x *MRunStageRequest) GetStageId() int32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *MRunStageRequest) GetRunShuffle() bool {
	if x != nil {
		return x.RunShuffle
	}
	return false
}

func (x *MRunStageRequest) GetPrepCollect() bool {
	if x != nil {
		return x.PrepCollect
	}
	return false
}

func (x *MRunStageRequest) GetPrepAccumulate() bool {
	if x != nil {
		return x.PrepAccumulate
	}
	return false
}

func (x *MRunStageRequest) GetAssignedBucket() uint64 {
	if x != nil {
		return x.AssignedBucket
	}
	return 0
}

func (x *MRunStageRequest) GetBuckets() []uint64 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *MRunStageRequest) GetWorkers() []*MWorkerDescriptor {
	if x != nil {
		return x.Workers
	}
	return nil
}

type MRunStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MRunStageResponse) Reset() {
	*x = MRunStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_execution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MRunStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MRunStageResponse) ProtoMessage() {}

func (x *MRunStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_s_execution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MRunStageResponse.ProtoReflect.Descriptor instead.
func (*MRunStageResponse) Descriptor() ([]byte, []int) {
	return file_s_execution_proto_rawDescGZIP(), []int{1}
}

var File_s_execution_proto protoreflect.FileDescriptor

var file_s_execution_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x0f, 0x73, 0x5f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x10, 0x4d, 0x52,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x53,
	0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x75,
	0x6e, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x70,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70,
	0x72, 0x65, 0x70, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72,
	0x65, 0x70, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x70, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x07, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x42, 0x02, 0x10, 0x01, 0x52,
	0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x52,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x4f, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x52, 0x75,
	0x6e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x69, 0x66, 0x2f, 0x73, 0x69, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_execution_proto_rawDescOnce sync.Once
	file_s_execution_proto_rawDescData = file_s_execution_proto_rawDesc
)

func file_s_execution_proto_rawDescGZIP() []byte {
	file_s_execution_proto_rawDescOnce.Do(func() {
		file_s_execution_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_execution_proto_rawDescData)
	})
	return file_s_execution_proto_rawDescData
}

var file_s_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s_execution_proto_goTypes = []interface{}{
	(*MRunStageRequest)(nil),  // 0: rpc.MRunStageRequest
	(*MRunStageResponse)(nil), // 1: rpc.MRunStageResponse
	(*MWorkerDescriptor)(nil), // 2: rpc.MWorkerDescriptor
}
var file_s_execution_proto_depIdxs = []int32{
	2, // 0: rpc.MRunStageRequest.workers:type_name -> rpc.MWorkerDescriptor
	0, // 1: rpc.ExecutionService.RunStage:input_type -> rpc.MRunStageRequest
	1, // 2: rpc.ExecutionService.RunStage:output_type -> rpc.MRunStageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s_execution_proto_init() }
func file_s_execution_proto_init() {
	if File_s_execution_proto != nil {
		return
	}
	file_s_cluster_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_s_execution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MRunStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_execution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MRunStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_execution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s_execution_proto_goTypes,
		DependencyIndexes: file_s_execution_proto_depIdxs,
		MessageInfos:      file_s_execution_proto_msgTypes,
	}.Build()
	File_s_execution_proto = out.File
	file_s_execution_proto_rawDesc = nil
	file_s_execution_proto_goTypes = nil
	file_s_execution_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutionServiceClient interface {
	RunStage(ctx context.Context, in *MRunStageRequest, opts ...grpc.CallOption) (*MRunStageResponse, error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) RunStage(ctx context.Context, in *MRunStageRequest, opts ...grpc.CallOption) (*MRunStageResponse, error) {
	out := new(MRunStageResponse)
	err := c.cc.Invoke(ctx, "/rpc.ExecutionService/RunStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionServiceServer is the server API for ExecutionService service.
type ExecutionServiceServer interface {
	RunStage(context.Context, *MRunStageRequest) (*MRunStageResponse, error)
}

// UnimplementedExecutionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExecutionServiceServer struct {
}

func (*UnimplementedExecutionServiceServer) RunStage(context.Context, *MRunStageRequest) (*MRunStageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStage not implemented")
}

func RegisterExecutionServiceServer(s *grpc.Server, srv ExecutionServiceServer) {
	s.RegisterService(&_ExecutionService_serviceDesc, srv)
}

func _ExecutionService_RunStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MRunStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RunStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ExecutionService/RunStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RunStage(ctx, req.(*MRunStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecutionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStage",
			Handler:    _ExecutionService_RunStage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s_execution.proto",
}
