// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s_stats.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MStatisticsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MStatisticsRequest) Reset()         { *m = MStatisticsRequest{} }
func (m *MStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*MStatisticsRequest) ProtoMessage()    {}
func (*MStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b2d114a090cdf0a, []int{0}
}

func (m *MStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MStatisticsRequest.Unmarshal(m, b)
}
func (m *MStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MStatisticsRequest.Marshal(b, m, deterministic)
}
func (m *MStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MStatisticsRequest.Merge(m, src)
}
func (m *MStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_MStatisticsRequest.Size(m)
}
func (m *MStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MStatisticsRequest proto.InternalMessageInfo

type MStatisticsResponse struct {
	Started                     bool     `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Finished                    bool     `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	StartTime                   int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	TotalRuntime                int64    `protobuf:"varint,4,opt,name=totalRuntime,proto3" json:"totalRuntime,omitempty"`
	RowsProcessed               []int64  `protobuf:"varint,5,rep,packed,name=rowsProcessed,proto3" json:"rowsProcessed,omitempty"`
	PartitionsProcessed         []int64  `protobuf:"varint,6,rep,packed,name=partitionsProcessed,proto3" json:"partitionsProcessed,omitempty"`
	RecentPartitionRuntimes     []int64  `protobuf:"varint,7,rep,packed,name=recentPartitionRuntimes,proto3" json:"recentPartitionRuntimes,omitempty"`
	RecentPartitionRuntimesHead int32    `protobuf:"varint,8,opt,name=recentPartitionRuntimesHead,proto3" json:"recentPartitionRuntimesHead,omitempty"`
	StageRuntimes               []int64  `protobuf:"varint,9,rep,packed,name=stageRuntimes,proto3" json:"stageRuntimes,omitempty"`
	TransformPhaseRuntimes      []int64  `protobuf:"varint,10,rep,packed,name=transformPhaseRuntimes,proto3" json:"transformPhaseRuntimes,omitempty"`
	ShufflePhaseRuntimes        []int64  `protobuf:"varint,11,rep,packed,name=shufflePhaseRuntimes,proto3" json:"shufflePhaseRuntimes,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *MStatisticsResponse) Reset()         { *m = MStatisticsResponse{} }
func (m *MStatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*MStatisticsResponse) ProtoMessage()    {}
func (*MStatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b2d114a090cdf0a, []int{1}
}

func (m *MStatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MStatisticsResponse.Unmarshal(m, b)
}
func (m *MStatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MStatisticsResponse.Marshal(b, m, deterministic)
}
func (m *MStatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MStatisticsResponse.Merge(m, src)
}
func (m *MStatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_MStatisticsResponse.Size(m)
}
func (m *MStatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MStatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MStatisticsResponse proto.InternalMessageInfo

func (m *MStatisticsResponse) GetStarted() bool {
	if m != nil {
		return m.Started
	}
	return false
}

func (m *MStatisticsResponse) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *MStatisticsResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *MStatisticsResponse) GetTotalRuntime() int64 {
	if m != nil {
		return m.TotalRuntime
	}
	return 0
}

func (m *MStatisticsResponse) GetRowsProcessed() []int64 {
	if m != nil {
		return m.RowsProcessed
	}
	return nil
}

func (m *MStatisticsResponse) GetPartitionsProcessed() []int64 {
	if m != nil {
		return m.PartitionsProcessed
	}
	return nil
}

func (m *MStatisticsResponse) GetRecentPartitionRuntimes() []int64 {
	if m != nil {
		return m.RecentPartitionRuntimes
	}
	return nil
}

func (m *MStatisticsResponse) GetRecentPartitionRuntimesHead() int32 {
	if m != nil {
		return m.RecentPartitionRuntimesHead
	}
	return 0
}

func (m *MStatisticsResponse) GetStageRuntimes() []int64 {
	if m != nil {
		return m.StageRuntimes
	}
	return nil
}

func (m *MStatisticsResponse) GetTransformPhaseRuntimes() []int64 {
	if m != nil {
		return m.TransformPhaseRuntimes
	}
	return nil
}

func (m *MStatisticsResponse) GetShufflePhaseRuntimes() []int64 {
	if m != nil {
		return m.ShufflePhaseRuntimes
	}
	return nil
}

type MClusterStatisticsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MClusterStatisticsRequest) Reset()         { *m = MClusterStatisticsRequest{} }
func (m *MClusterStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*MClusterStatisticsRequest) ProtoMessage()    {}
func (*MClusterStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b2d114a090cdf0a, []int{2}
}

func (m *MClusterStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MClusterStatisticsRequest.Unmarshal(m, b)
}
func (m *MClusterStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MClusterStatisticsRequest.Marshal(b, m, deterministic)
}
func (m *MClusterStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MClusterStatisticsRequest.Merge(m, src)
}
func (m *MClusterStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_MClusterStatisticsRequest.Size(m)
}
func (m *MClusterStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MClusterStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MClusterStatisticsRequest proto.InternalMessageInfo

type MClusterStatisticsResponse struct {
	ClusterStats         map[string]*MStatisticsResponse `protobuf:"bytes,1,rep,name=clusterStats,proto3" json:"clusterStats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *MClusterStatisticsResponse) Reset()         { *m = MClusterStatisticsResponse{} }
func (m *MClusterStatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*MClusterStatisticsResponse) ProtoMessage()    {}
func (*MClusterStatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b2d114a090cdf0a, []int{3}
}

func (m *MClusterStatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MClusterStatisticsResponse.Unmarshal(m, b)
}
func (m *MClusterStatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MClusterStatisticsResponse.Marshal(b, m, deterministic)
}
func (m *MClusterStatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MClusterStatisticsResponse.Merge(m, src)
}
func (m *MClusterStatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_MClusterStatisticsResponse.Size(m)
}
func (m *MClusterStatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MClusterStatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MClusterStatisticsResponse proto.InternalMessageInfo

func (m *MClusterStatisticsResponse) GetClusterStats() map[string]*MStatisticsResponse {
	if m != nil {
		return m.ClusterStats
	}
	return nil
}

func init() {
	proto.RegisterType((*MStatisticsRequest)(nil), "rpc.MStatisticsRequest")
	proto.RegisterType((*MStatisticsResponse)(nil), "rpc.MStatisticsResponse")
	proto.RegisterType((*MClusterStatisticsRequest)(nil), "rpc.MClusterStatisticsRequest")
	proto.RegisterType((*MClusterStatisticsResponse)(nil), "rpc.MClusterStatisticsResponse")
	proto.RegisterMapType((map[string]*MStatisticsResponse)(nil), "rpc.MClusterStatisticsResponse.ClusterStatsEntry")
}

func init() {
	proto.RegisterFile("s_stats.proto", fileDescriptor_2b2d114a090cdf0a)
}

var fileDescriptor_2b2d114a090cdf0a = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0x9a, 0xb4, 0xc9, 0xa4, 0x95, 0xc8, 0xb6, 0xa2, 0x4b, 0x8a, 0x20, 0xb2, 0x38,
	0xf8, 0x64, 0x81, 0x91, 0x50, 0xc5, 0x09, 0x09, 0x21, 0xf5, 0x52, 0x29, 0xda, 0x00, 0x12, 0x17,
	0xd0, 0x62, 0x4f, 0xc8, 0x0a, 0xd7, 0x6b, 0x76, 0xc6, 0x41, 0x7d, 0x49, 0x5e, 0x86, 0x17, 0x40,
	0xd9, 0x24, 0x4d, 0xac, 0xc4, 0x70, 0xf3, 0xce, 0xff, 0xcd, 0xff, 0x6b, 0x46, 0x63, 0x38, 0xa5,
	0xaf, 0xc4, 0x9a, 0x29, 0xa9, 0x9c, 0x65, 0x2b, 0x42, 0x57, 0x65, 0xd1, 0x39, 0x88, 0x9b, 0x09,
	0x6b, 0x36, 0xc4, 0x26, 0x23, 0x85, 0x3f, 0x6b, 0x24, 0x8e, 0xfe, 0x84, 0x70, 0xd6, 0x28, 0x53,
	0x65, 0x4b, 0x42, 0x21, 0xe1, 0x98, 0x58, 0x3b, 0xc6, 0x5c, 0x06, 0xa3, 0x20, 0xee, 0xaa, 0xf5,
	0x53, 0x0c, 0xa1, 0x3b, 0x35, 0xa5, 0xa1, 0x19, 0xe6, 0xf2, 0xd0, 0x4b, 0xf7, 0x6f, 0xf1, 0x04,
	0x7a, 0x1e, 0xfb, 0x60, 0x6e, 0x51, 0x86, 0xa3, 0x20, 0x0e, 0xd5, 0xa6, 0x20, 0x22, 0x38, 0x61,
	0xcb, 0xba, 0x50, 0x75, 0xc9, 0x0b, 0xe0, 0x81, 0x07, 0x1a, 0x35, 0xf1, 0x1c, 0x4e, 0x9d, 0xfd,
	0x45, 0x63, 0x67, 0x33, 0x24, 0xc2, 0x5c, 0x76, 0x46, 0x61, 0x1c, 0xaa, 0x66, 0x51, 0xbc, 0x80,
	0xb3, 0x4a, 0x3b, 0x36, 0x6c, 0x6c, 0xb9, 0xc5, 0x1e, 0x79, 0x76, 0x9f, 0x24, 0xae, 0xe0, 0xc2,
	0x61, 0x86, 0x25, 0x8f, 0xd7, 0xe2, 0x2a, 0x91, 0xe4, 0xb1, 0xef, 0x6a, 0x93, 0xc5, 0x5b, 0xb8,
	0x6c, 0x91, 0xae, 0x51, 0xe7, 0xb2, 0x3b, 0x0a, 0xe2, 0x8e, 0xfa, 0x17, 0xb2, 0x98, 0x89, 0x58,
	0x7f, 0xc7, 0xfb, 0xc4, 0xde, 0x72, 0xa6, 0x46, 0x51, 0xbc, 0x86, 0x47, 0xec, 0x74, 0x49, 0x53,
	0xeb, 0x6e, 0xc7, 0x33, 0x4d, 0x1b, 0x1c, 0x3c, 0xde, 0xa2, 0x8a, 0x14, 0xce, 0x69, 0x56, 0x4f,
	0xa7, 0x05, 0x36, 0xbb, 0xfa, 0xbe, 0x6b, 0xaf, 0x16, 0x5d, 0xc2, 0xe3, 0x9b, 0x77, 0x45, 0x4d,
	0x8c, 0x6e, 0xf7, 0x24, 0x7e, 0x07, 0x30, 0xdc, 0xa7, 0xae, 0x2e, 0xe3, 0x23, 0x9c, 0x64, 0x1b,
	0x91, 0x64, 0x30, 0x0a, 0xe3, 0x7e, 0xfa, 0x32, 0x71, 0x55, 0x96, 0xb4, 0xb7, 0x25, 0x5b, 0x0a,
	0xbd, 0x2f, 0xd9, 0xdd, 0xa9, 0x86, 0xcd, 0xf0, 0x33, 0x0c, 0x76, 0x10, 0xf1, 0x10, 0xc2, 0x1f,
	0x78, 0xe7, 0x2f, 0xb0, 0xa7, 0x16, 0x9f, 0x22, 0x81, 0xce, 0x5c, 0x17, 0x35, 0xfa, 0xd3, 0xeb,
	0xa7, 0x72, 0x19, 0xbb, 0x9b, 0xa7, 0x96, 0xd8, 0x9b, 0xc3, 0xab, 0x20, 0xfd, 0x02, 0xc2, 0x7b,
	0x4e, 0x6c, 0xed, 0x32, 0x9c, 0xa0, 0x9b, 0x9b, 0x0c, 0xc5, 0x35, 0x0c, 0xc6, 0xce, 0xce, 0x4d,
	0x8e, 0x9b, 0x6e, 0x71, 0xb1, 0xeb, 0xe7, 0x97, 0x32, 0x6c, 0x0d, 0x8a, 0x0e, 0xd2, 0x62, 0xed,
	0x8f, 0x6e, 0x8e, 0x6e, 0xed, 0xff, 0x09, 0x06, 0xab, 0x7d, 0x6f, 0xf9, 0x3f, 0x6d, 0x5d, 0xd3,
	0x32, 0xe6, 0xd9, 0x7f, 0xd6, 0x18, 0x1d, 0x7c, 0x3b, 0xf2, 0xff, 0xf4, 0xab, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0xa4, 0xca, 0x58, 0xe4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StatsSourceServiceClient is the client API for StatsSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsSourceServiceClient interface {
	ProvideStatistics(ctx context.Context, in *MStatisticsRequest, opts ...grpc.CallOption) (*MStatisticsResponse, error)
}

type statsSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsSourceServiceClient(cc grpc.ClientConnInterface) StatsSourceServiceClient {
	return &statsSourceServiceClient{cc}
}

func (c *statsSourceServiceClient) ProvideStatistics(ctx context.Context, in *MStatisticsRequest, opts ...grpc.CallOption) (*MStatisticsResponse, error) {
	out := new(MStatisticsResponse)
	err := c.cc.Invoke(ctx, "/rpc.StatsSourceService/ProvideStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsSourceServiceServer is the server API for StatsSourceService service.
type StatsSourceServiceServer interface {
	ProvideStatistics(context.Context, *MStatisticsRequest) (*MStatisticsResponse, error)
}

// UnimplementedStatsSourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatsSourceServiceServer struct {
}

func (*UnimplementedStatsSourceServiceServer) ProvideStatistics(ctx context.Context, req *MStatisticsRequest) (*MStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvideStatistics not implemented")
}

func RegisterStatsSourceServiceServer(s *grpc.Server, srv StatsSourceServiceServer) {
	s.RegisterService(&_StatsSourceService_serviceDesc, srv)
}

func _StatsSourceService_ProvideStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsSourceServiceServer).ProvideStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.StatsSourceService/ProvideStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsSourceServiceServer).ProvideStatistics(ctx, req.(*MStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatsSourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.StatsSourceService",
	HandlerType: (*StatsSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvideStatistics",
			Handler:    _StatsSourceService_ProvideStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s_stats.proto",
}

// StatsServerServiceClient is the client API for StatsServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsServerServiceClient interface {
	RuntimeStatistics(ctx context.Context, in *MClusterStatisticsRequest, opts ...grpc.CallOption) (*MClusterStatisticsResponse, error)
}

type statsServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServerServiceClient(cc grpc.ClientConnInterface) StatsServerServiceClient {
	return &statsServerServiceClient{cc}
}

func (c *statsServerServiceClient) RuntimeStatistics(ctx context.Context, in *MClusterStatisticsRequest, opts ...grpc.CallOption) (*MClusterStatisticsResponse, error) {
	out := new(MClusterStatisticsResponse)
	err := c.cc.Invoke(ctx, "/rpc.StatsServerService/RuntimeStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServerServiceServer is the server API for StatsServerService service.
type StatsServerServiceServer interface {
	RuntimeStatistics(context.Context, *MClusterStatisticsRequest) (*MClusterStatisticsResponse, error)
}

// UnimplementedStatsServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatsServerServiceServer struct {
}

func (*UnimplementedStatsServerServiceServer) RuntimeStatistics(ctx context.Context, req *MClusterStatisticsRequest) (*MClusterStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeStatistics not implemented")
}

func RegisterStatsServerServiceServer(s *grpc.Server, srv StatsServerServiceServer) {
	s.RegisterService(&_StatsServerService_serviceDesc, srv)
}

func _StatsServerService_RuntimeStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MClusterStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServerServiceServer).RuntimeStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.StatsServerService/RuntimeStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServerServiceServer).RuntimeStatistics(ctx, req.(*MClusterStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatsServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.StatsServerService",
	HandlerType: (*StatsServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RuntimeStatistics",
			Handler:    _StatsServerService_RuntimeStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s_stats.proto",
}
