package partition

import (
	"fmt"

	"github.com/go-sif/sif"
	itypes "github.com/go-sif/sif/internal/types"
)

// createCloneablePartition creates a new Partition containing an empty byte array and a schema
func createCloneablePartition(maxRows int, schema sif.Schema) itypes.CloneablePartition {
	return createPartitionImpl(maxRows, schema)
}

// GetRowMeta retrieves specific row metadata from this Partition
func (p *partitionImpl) GetRowMeta(rowNum int) []byte {
	start := rowNum * p.schema.NumColumns()
	end := start + p.schema.NumColumns()
	return p.rowMeta[start:end]
}

// GetRowMetaRange retrieves an arbitrary range of bytes from the row meta
func (p *partitionImpl) GetRowMetaRange(start int, end int) []byte {
	maxByte := p.numRows * p.schema.NumColumns()
	if end > maxByte {
		end = maxByte
	}
	return p.rowMeta[start:end]
}

// GetRowData retrieves a specific row from this Partition
func (p *partitionImpl) GetRowData(rowNum int) []byte {
	start := rowNum * p.schema.Size()
	end := start + p.schema.Size()
	return p.rows[start:end]
}

// GetRowDataRange retrieves an arbitrary range of bytes from the row data
func (p *partitionImpl) GetRowDataRange(start int, end int) []byte {
	maxByte := p.numRows * p.schema.Size()
	if end > maxByte {
		end = maxByte
	}
	return p.rows[start:end]
}

// GetVarRowData retrieves the variable-length data for a given row from this Partition
func (p *partitionImpl) GetVarRowData(rowNum int) map[string]interface{} {
	if p.varRowData[rowNum] == nil {
		p.varRowData[rowNum] = make(map[string]interface{})
	}
	return p.varRowData[rowNum]
}

// GetSerializedVarRowData retrieves the serialized variable-length data for a given row from this Partition
func (p *partitionImpl) GetSerializedVarRowData(rowNum int) map[string][]byte {
	if p.serializedVarRowData[rowNum] == nil {
		p.serializedVarRowData[rowNum] = make(map[string][]byte)
	}
	return p.serializedVarRowData[rowNum]
}

// GetSchema retrieves the Schema from the most recent task that manipulated this Partition. Represents the client-facing schema.
func (p *partitionImpl) GetSchema() sif.Schema {
	return p.schema
}

// GetIsKeyed returns true iff this Partition has been keyed with KeyRows
func (p *partitionImpl) GetIsKeyed() bool {
	return p.isKeyed
}

// GetKey returns the shuffle key for a row, as generated by KeyRows
func (p *partitionImpl) GetKey(rowNum int) (uint64, error) {
	if !p.isKeyed {
		return 0, fmt.Errorf("Partition is not keyed")
	}
	return p.keys[rowNum], nil
}

// GetKeyRange returns a range of shuffle keys for a row, as generated by KeyRows, starting at rowNum
func (p *partitionImpl) GetKeyRange(rowNum int, numRows int) []uint64 {
	end := rowNum + numRows
	if end > p.numRows {
		end = p.numRows
	}
	return p.keys[rowNum:end]
}
