name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: "Tests (${{ matrix.os }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15']
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 1 }
    - uses: actions/setup-go@v2
      with: { go-version: "${{ matrix.go }}" }
    - uses: arduino/setup-protoc@v1
    - run: go version
    - run: make dependencies
    - run: make cover
    - uses: codecov/codecov-action@v1
      with:
        file: cover.out
